---
# tasks file for role_nutanix_prism_monitor_task
- name: Setup connection to Nutanix API
  ansible.builtin.include_tasks: setup_api.yml

- name: Debug variables
  ansible.builtin.debug:
    var: "{{ item }}"
  loop:
    - nutanix_task_uuid
    - nutanix_task_retries
    - nutanix_task_retry_delay
  when:
    - nutanix_debug

- name: Nutanix_task_uuid not defined or is empty
  ansible.builtin.fail:
    msg: "nutanix_task_uuid must be defined"
  when:
    - nutanix_task_uuid == '' or not nutanix_task_uuid

- name: Monitor PE Task
  ansible.builtin.include_tasks: pe_monitor_task.yml
  when:
    - nutanix_endpoint_prism_type == 'pe'

- name: Monitor PC Task
  ansible.builtin.include_tasks: pc_monitor_task.yml
  when:
    - nutanix_endpoint_prism_type == 'pc'
