---
- name: "Monitoring PC task {{ role_nutanix_prism_monitor_task_uuid }}"
  ansible.builtin.uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/api/nutanix/v3/tasks/{{ role_nutanix_prism_monitor_task_uuid }}"
    method: GET
    validate_certs: "{{ role_nutanix_prism_monitor_task_host_validate_certs }}"
    status_code: 200
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
  ignore_errors: "{{ role_nutanix_prism_monitor_task_allow_failure }}"
  register: role_nutanix_prism_monitor_task_result
  until: >
    role_nutanix_prism_monitor_task_result.json.status | default('') | lower == 'succeeded' or
    role_nutanix_prism_monitor_task_result.json.status | default('') | lower == 'failed'
  retries: "{{ role_nutanix_prism_monitor_task_retries }}"
  delay: "{{ role_nutanix_prism_monitor_task_retry_delay }}"

- name: Debug role_nutanix_prism_monitor_task_result
  debug:
    var: role_nutanix_prism_monitor_task_result
  when:
    - role_nutanix_prism_monitor_task_debug

- name: "PC task failed {{ role_nutanix_prism_monitor_task_uuid }}."
  ansible.builtin.fail:
    msg:
      "{{ role_nutanix_prism_monitor_task_result.json.operation_type }} failed at {{ role_nutanix_prism_monitor_task_result.json.percentage_complete }}%. \
      Message: {{ role_nutanix_prism_monitor_task_result.json.progress_message }}"
  when: role_nutanix_prism_monitor_task_result.json.status | lower == 'failed'

- name: "PC task succeeded {{ role_nutanix_prism_monitor_task_uuid }}."
  ansible.builtin.debug:
    msg:
      "{{ role_nutanix_prism_monitor_task_result.json.operation_type }} succeeded. \
      Message: {{ role_nutanix_prism_monitor_task_result.json.progress_message }}"
  when:
    - role_nutanix_prism_monitor_task_result.json.status | lower == 'succeeded'
    - role_nutanix_prism_monitor_task_allow_failure
